### ISSUE TITLE
Refusing to use pkcon

### ISSUE THREAD

**Issue by 2eg01nd** [keygenqt/aurora-cli#13]
In newer versions of aurora, you won't be able to use pkcon to install regular applications.

**Comment by keygenqt** [comment]
Why? It works now. What new versions?

**Comment by DeSharky** [comment]
You need to install rpm's using APM

**Comment by 2eg01nd** [comment]
Yes, apm. 
Install: gdbus call --system --dest ru.omp.APM --object-path /ru/omp/APM --method ru.omp.APM.Install \"/home/defaultuser/$rpm_package\" \"{'ShowPrompt':<false>}\"
Remove: gdbus call --system --dest ru.omp.APM --object-path /ru/omp/APM --method ru.omp.APM.Remove \"$rpm_package\"
GetPackage: gdbus call --system --dest ru.omp.APM --object-path /ru/omp/APM --method ru.omp.APM.GetPackage \"$rpm_package\"
Maybe there are easier ways?

**Comment by keygenqt** [comment]
Add flag --apm for devices with APM
https://github.com/keygenqt/aurora-cli/blob/main/CHANGELOG.md#version-270-17052024
