### ISSUE TITLE
Not all recent versions are visible

### ISSUE THREAD

**Issue by Hatemsla** [keygenqt/aurora-cli#18]
I want to install sdk version 5.1.0.100, but the latest one available to me (even with the --show-all tag) this is 5.1.0.24
```
hatemsla@Hatemsla:~$ aurora-cli sdk install -a
Waiting for a response from the server...
Select version index
1: 5.1.0
2: 5.0.1
3: 5.0.0
4: 4.1.0
5: 4.0.2
6: 4.0.1

Select index: 1
Download: AuroraSDK-5.1.0.24-base-release-linux-64-online-24.03.22-12.30.13.run
```
aurora-cli version
```
hatemsla@Hatemsla:~$ aurora-cli --version
aurora-cli, version 2.7.0
```

**Comment by keygenqt** [comment]
Это зависит от репозитория. Логики в структурах директорий репозитория проследить сложно. Единая - версию доступную ищем в AppSDK, там 24

**Comment by keygenqt** [comment]
Добавил фикс для 5.1 в 3.0.0.20
