### ISSUE TITLE
ЧАТ

### ISSUE THREAD

**Issue by nikitakolesnikov13** [keygenqt/aurora-cli#20]
В каком чате обсуждаются баги и фичи, хотел бы принять участие?

**Comment by keygenqt** [comment]
Здесь можно фиксировать баги, предлагать фичи. Отдельного чата нет.

**Comment by keygenqt** [comment]
Баги фиксируются в issue если люди их находят. Повые фичи не планировал, всегда можно предложить их здесь же в issue. Что нужно сделать это протестировать приложение на разных дистрибутивах (kali, debian, arch etc)  и описать нюансы здесь https://aurora-cli.keygenqt.com/install. Есть запросы на поддержку работы приложения в WSL.
