### ISSUE TITLE
Can't sign package if a passphrase needed.

### ISSUE THREAD

**Issue by BEEugene** [keygenqt/aurora-cli#25]
Если ключ разработчика требует кодовую фразу (является зашифрованным) - подписания не происходит и никакой ошибки не пробрасывается в терминал.

**Comment by keygenqt** [comment]
Спасибо! Проблема ясна, как найду такой ключ и немного времени можно будет добавить возможность работать с ключами имеющими кодовую фразу.

**Comment by BEEugene** [comment]
Если тыкнешь, где добавить, могу поэкспериментировать со своим ключом.

> Спасибо! Проблема ясна, как найду такой ключ и немного времени можно будет добавить возможность работать с ключами имеющими кодовую фразу.

**Comment by keygenqt** [comment]
https://github.com/keygenqt/aurora-cli/commit/3bc42a1140c0bd81abff11288f0073b591873575
