### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by trofim373** [keygenqt/aurora-cli#29]
При установке на Ubuntu 24.10 используя команды 
sudo apt update
sudo apt install python3-pip
python3 -m pip install aurora-cli --break-system-packages
выходит ошибка:
Defaulting to user installation because normal site-packages is not writeable
Collecting aurora-cli
  Using cached aurora_cli-3.0.10.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: click>=8.1.7 in /usr/lib/python3/dist-packages (from aurora-cli) (8.1.7)
Requirement already satisfied: requests>=2.31.0 in /usr/lib/python3/dist-packages (from aurora-cli) (2.32.3)
Collecting alive-progress>=3.1.5 (from aurora-cli)
  Using cached alive_progress-3.2.0-py3-none-any.whl.metadata (70 kB)
Requirement already satisfied: pyYaml>=6.0.1 in /usr/lib/python3/dist-packages (from aurora-cli) (6.0.2)
Collecting paramiko>=3.4.0 (from aurora-cli)
  Using cached paramiko-3.5.0-py3-none-any.whl.metadata (4.4 kB)
Collecting cffi>=1.16.0 (from aurora-cli)
  Using cached cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting GitPython>=3.1.41 (from aurora-cli)
  Using cached GitPython-3.1.43-py3-none-any.whl.metadata (13 kB)
Collecting beautifulsoup4>=4.12.3 (from aurora-cli)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting weasyprint>=61.1 (from aurora-cli)
  Using cached weasyprint-62.3-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: pillow>=10.2.0 in /usr/lib/python3/dist-packages (from aurora-cli) (10.4.0)
Collecting diskcache>=5.6.3 (from aurora-cli)
  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting about-time==4.2.1 (from alive-progress>=3.1.5->aurora-cli)
  Using cached about_time-4.2.1-py3-none-any.whl.metadata (13 kB)
Collecting grapheme==0.6.0 (from alive-progress>=3.1.5->aurora-cli)
  Using cached grapheme-0.6.0.tar.gz (207 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_aixh2cw/grapheme_8a79e13e5fc2492db592eea936f3b06f/setup.py", line 2, in <module>
          from setuptools import setup, find_packages
      ImportError: cannot import name 'setup' from 'setuptools' (unknown location)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Все необходимые зависимости были установлены.

**Comment by keygenqt** [comment]
Спасибо, нужно будет проверить.

**Comment by keygenqt** [comment]
https://github.com/keygenqt/aurora-cli/commit/ffb39051a10d754b3eb6a834ac0705d8c57dbcc7
