### ISSUE TITLE
Doesn't work on FEDORA

### ISSUE THREAD

**Issue by trofim373** [keygenqt/aurora-cli#30]
Просьба адаптировать скрипт "aurora-cli psdk sudoers add" для Fedora, так как в ней он не срабатывает указывая, что недостаточно прав для добавления в Sudoers. Использование sudo не помогает.

**Comment by keygenqt** [comment]
Спасибо, рекомендованный дистрибутив Ubuntu, но надеюсь доберусь и до Fedora. Если есть возможность самостоятельно разобраться, буду рад пул-реквесту )

**Comment by keygenqt** [comment]
Пока так: https://github.com/keygenqt/aurora-cli/commit/a4e9ea42f5e4f42527d25846aff01f3c98e8902e
Фича с sudoers корретктно работат только на Ubuntu.
