### ISSUE TITLE
Wrong download url for Aurora SDK 5.1.3

### ISSUE THREAD

**Issue by 2eg01nd** [keygenqt/aurora-cli#31]
In version 5.1.3, the download path for the Platform SDK changed from PlatformSDK to AuroraPSDK.

**Comment by 2eg01nd** [comment]
In version 5.1.3, the download path for the Aurora SDK changed from AuroraSDK-base to AuroraSDK-MB2.

**Comment by keygenqt** [comment]
Fix https://github.com/keygenqt/aurora-cli/commit/e503a08e46b2ac3d33b40cfcf3234c94f4599ffa
