### ISSUE TITLE
Ошибка при получении списка расширений vscode

### ISSUE THREAD

**Issue by aospiridonov** [keygenqt/aurora-cli#32]
**Опишите ошибку**
Расширений usernamehw.errorlens ломает получение списка

**Чтобы воспроизвести**
Шаги для воспроизведения поведения:
1. Установить расширение vscode  ```ext install usernamehw.errorlens```
2. Запустить Aurora Toolbox
3.  Visual Studio Code

**Ожидаемое поведение**
Получить экран с настройками vscode

**Пожалуйста, заполните следующую информацию:**
- ОС: Ubuntu 24.04
- Версия Aurora Toolbox: 0.0.9
- Версия Aurora CLI 3.0.14

**Comment by keygenqt** [comment]
https://github.com/keygenqt/aurora-cli/commit/c078202c83c90b019943fabf4b042ff0e9037dee
