### ISSUE TITLE
Slow loading SDK

### ISSUE THREAD

**Issue by Overman775** [keygenqt/aurora-cli#6]
Hi! thanks for your job )

The problem is the slow loading of the aurora sdk when run command ` aurora-cli sdk install`.  Shows an approximate download time of 9k. I checked in the browser and wget, it loads sdk quickly

![image](https://github.com/keygenqt/aurora-cli/assets/47769319/4e63fc88-3409-4ceb-ac47-12158d219b9c)

aurorora cli version 2.2.0, runing in wsl 2 on ubuntu 22

**Comment by Overman775** [comment]
Same bug with downloading psdk

**Comment by keygenqt** [comment]
Fix 2.2.5
